version: '3'
services:
  instrument-test:
    depends_on:
    - db
    build: .
    ports:
     - "8090:80"
    volumes:
     - .:/var/www
  db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     ports:
          - "13306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: instrument
       MYSQL_USER: instrument
       MYSQL_PASSWORD: instrument